language: rust
sudo: false

cache:
  directories:
    - /home/travis/.cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "Adiatma Kamarudin"
    - git config --local user.email "adiatma9024@gmail.com"
    - name="cli-covid19-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/cli-covid19 $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: $GITHUB_API_TOKEN
    file: cli-covid19-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true

RELEASE_TO_CRATE: &RELEASE_TO_CRATE
  deploy:
    provider: cargo
    token: $CARGO_TOKEN
    on:
      branch: master
      tags: true

jobs:
  include:
  
  - stage: "Testing & Build"
    name: Tests
    env: RUST_BACKTRACE=1
    rust: stable
    script:
    - cargo build
  
  - stage: "Release" 
    name: Release to crate
    rust: stable
    <<: *RELEASE_TO_CRATE
  
  - stage: "Release"
    name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - stage: "Release" 
    name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never

