language: rust
sudo: false

cache:
  directories:
    - /home/travis/.cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "adiatma"
    - git config --local user.email "adiatma9024@gmail.com"
    - name="cli-covid19-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - chmod +x $name
    - chmod +x target
    - cp target/$TARGET/release/cli-covid19 /$name
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file: cli-covid19-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true

jobs:
  include:
  - name: Tests
    env: RUST_BACKTRACE=1
    rust: nightly
    script:
    - cargo test
  
  - name: Release to crate
    deploy:
      provider: cargo
      token: $CARGO_TOKEN
      on:
        branch: master
        tags: true
  
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --features vendored-openssl
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never

